-- WikiViewer Database Schema (Apache Derby / SQL-92)

-- Table: CATEGORY
-- Stores the user-defined categories for organizing articles.
CREATE TABLE CATEGORY (
    ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT UNQ_CATEGORY_NAME UNIQUE (NAME)
);

-- Table: ARTICLE
-- Stores Wikipedia articles selected by the user, enriched with metadata.
CREATE TABLE ARTICLE (
    ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    TITLE VARCHAR(255) NOT NULL,
    SNIPPET CLOB,
    TIMESTAMP TIMESTAMP,
    COMMENTS CLOB,
    RATING INTEGER,
    PAGEID INTEGER,
    CATEGORY_ID BIGINT,
    PRIMARY KEY (ID),
    CONSTRAINT UNQ_ARTICLE_PAGEID UNIQUE (PAGEID),
    CONSTRAINT FK_ARTICLE_CATEGORY_ID FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (ID)
);

-- Table: SEARCH_KEYWORD
-- Tracks user search history for statistical analysis.
CREATE TABLE SEARCH_KEYWORD (
    ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    KEYWORD VARCHAR(255) NOT NULL,
    SEARCHCOUNT INTEGER NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT UNQ_KEYWORD UNIQUE (KEYWORD)
);
